### ISSUE TITLE
ThunderThings app not installing

### ISSUE THREAD

**Issue by thicke** [snchong/thunderthings#1]
![Screenshot_3_20_22__3_56_PM](https://user-images.githubusercontent.com/4109704/159185586-be8f930e-3c9d-4bfe-af14-c1624256aeb4.png)

I am getting this error when trying to install the app. 

The visit website button goes to the following link. 

https://py2app.readthedocs.io/en/latest/debugging.html

Output from the command line wasn't real helpful. 

> Last login: Fri Mar 18 19:50:46 on ttys000
> /Applications/ThunderThings.app/Contents/MacOS/ThunderThings ; exit;            
> username@ComputerName ~ % /Applications/ThunderThings.app/Contents/MacOS/ThunderThings ; exit;

**Comment by snchong** [comment]
Thanks, the error just means that the application (which is implemented in Python) exited with an error. Please try running `env APPLAUNCHED="Y" /Applications/ThunderThings.app/Contents/MacOS/ThunderThings` from the command line and paste the output here.

**Comment by thicke** [comment]
Here you go. 

Traceback (most recent call last):
  File "/Applications/ThunderThings.app/Contents/Resources/__boot__.py", line 130, in <module>
    _run()
  File "/Applications/ThunderThings.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/ThunderThings.app/Contents/Resources/ThunderThings.py", line 139, in <module>
    installFiles()
  File "/Applications/ThunderThings.app/Contents/Resources/ThunderThings.py", line 98, in installFiles
    if not writeToFile(userfile, js):
  File "/Applications/ThunderThings.app/Contents/Resources/ThunderThings.py", line 78, in writeToFile
    f = open(filename, "w+")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Library/Application Support/Mozilla/NativeMessagingHosts/thunderthings.json'
2022-03-20 20:47:59.943 ThunderThings[13031:6728821] Launch error
2022-03-20 20:47:59.943 ThunderThings[13031:6728821] Launch error
See the py2app website for debugging launch issues

**Comment by snchong** [comment]
Thanks, it looks like the directory `/Users/username/Library/Application Support/Mozilla/NativeMessagingHosts/` doesn't exist. You can fix this by running the following on the command line:

```
mkdir -p "/Users/username/Library/Application Support/Mozilla/NativeMessagingHosts/"
```

and then running the app again. Please let me know if that worked.

I'll fix the app to handle this case correctly.

**Comment by thicke** [comment]
Yep. I created that right after sending that. It worked. Thanks!
